### ISSUE TITLE
Crash on Server (java.lang.ClassNotFoundException: gregfluxologyCommonProxy) [Cleanroom]

### ISSUE THREAD

**Issue by aking4125** [MCTian-mi/Gregfluxology#1]
Hello, upon loading this mod on the server. The server crashes with the following report:
[crash-2024-10-11_08.23.25-server.txt](https://github.com/user-attachments/files/17342564/crash-2024-10-11_08.23.25-server.txt)

We are using [Cleanroom](https://github.com/CleanroomMC/Cleanroom) which could be part of the issue. But it works in this environment in single-player. Any ideas?

[debug.log](https://github.com/user-attachments/files/17342565/debug.log)

**Comment by MCTian-mi** [comment]
hmmm
it worked fine for me
will check this later
