### ISSUE TITLE
version 1.20.1

### ISSUE THREAD

**Issue by Soophine** [MCTian-mi/Gregfluxology#4]
java.lang.NoSuchMethodException: gregfluxology.Gregfluxology.<init>()

**Comment by MCTian-mi** [comment]
are you on neoforge legacy or?

**Comment by Soophine** [comment]
forge 47.3.6
gtceu 1.4.6

**Comment by MCTian-mi** [comment]
just try latest forge (47.3.22)

**Comment by Soophine** [comment]
solved
